{% set name = "apache-airflow-providers-apache-iceberg" %}
{% set version = "1.3.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_iceberg-{{ version }}.tar.gz
  sha256: 3258dea50522a8e707d7216d85ffd118ba04e819a7506ff537fab853cd0eeafc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0

test:
  imports:
    - airflow.providers.apache.iceberg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-iceberg for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/apache/iceberg/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-iceberg/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
