{% set name = "apache-airflow-providers-apache-iceberg" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_iceberg-{{ version }}.tar.gz
  sha256: 39dc2983615b0584ba7fb70dd8222a20c33d1cf7c535f4ecd64438fec46bad4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.0
    - apache-airflow >=2.7.0

test:
  imports:
    - airflow.providers.apache.iceberg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-iceberg for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/iceberg/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-iceberg/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
